pipeline {
    agent any
    tools {
        maven 'Maven'   // must match the name configured in Manage Jenkins > Tools
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar, target/site/jacoco/**', fingerprint: true
	    }
        }
    }
}
