pipeline {
    agent any
    tools {
        maven 'Maven'   // must match the name configured in Manage Jenkins > Tools
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -f starter/pom.xml clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B -f starter/pom.xml test'
            }
            post {
                always {
                    junit 'starter/target/surefire-reports/*.xml'
                }
            }
        }n
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'starter/target/*.jar', fingerprint: true
            }
        }
    }
}
